{% set name = "h3" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/uber/h3/archive/v{{ version }}.tar.gz
  sha256: 01891901707c6430caaea7e645ff5ac6980cae166094a6f924ded197e5774a19

build:
  number: 0
  skip: true  # [win and vc<14]
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make

test:
  commands:
    - test -f $PREFIX/lib/libh3${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/h3/h3api.h  # [unix]
    - test -f %PREFIX%\Library\lib\h3.dll  # [win]
    - test -f %PREFIX%\Library\include\h3\h3api.h  # [win]

about:
  home: https://github.com/uber/h3
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Hexagonal hierarchical geospatial indexing system
  doc_url: https://uber.github.io/h3/
  dev_url: https://github.com/uber/h3

extra:
  recipe-maintainers:
    - mxr-conda
    - geoHeil
    - benhuff
    - oblute
