{% set name = "h3" %}
{% set version = "3.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/uber/h3/archive/v{{ version }}.tar.gz
  sha256: 3ba219959ecb0ef6956f05113aa659d7b605e4eebbdca561b8243ce309e4684e
  patches:
    - LIB_source_files.patch  # [win]

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make

test:
  commands:
    - test -f $PREFIX/lib/libh3${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/h3/h3api.h  # [unix]
    - test -f %PREFIX%\Library\lib\h3.dll  # [win]
    - test -f %PREFIX%\Library\include\h3\h3api.h  # [win]

about:
  home: https://github.com/uber/h3
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Hexagonal hierarchical geospatial indexing system'
  doc_url: https://uber.github.io/h3/
  dev_url: https://github.com/uber/h3

extra:
  recipe-maintainers:
    - geoHeil
    - benhuff
    - oblute
