{% set name = "h3" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/uber/h3/archive/v{{ version }}.tar.gz
  sha256: 438db46fc2b388785d2a0d8e26aa5509739240a7b50b2510c416778d871a4e11

build:
  number: 0
  skip: true  # [win and vc<14]
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make

test:
  commands:
    - test -f $PREFIX/lib/libh3${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/h3/h3api.h  # [unix]
    - test -f %PREFIX%\Library\lib\h3.dll  # [win]
    - test -f %PREFIX%\Library\include\h3\h3api.h  # [win]

about:
  home: https://github.com/uber/h3
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Hexagonal hierarchical geospatial indexing system
  doc_url: https://uber.github.io/h3/
  dev_url: https://github.com/uber/h3

extra:
  recipe-maintainers:
    - mxr-conda
    - geoHeil
    - benhuff
    - oblute
