schema_version: 1

context:
  name: h3
  version: "4.3.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/uber/h3/archive/v${{ version }}.tar.gz
  sha256: a47cfa36e255e4bf16c63015aaff8e6fe2afc14ffaa3f6b281718158446c0e9b

build:
  number: 0
  skip: win and vc<14
  dynamic_linking:
    missing_dso_allowlist:
      - "*"

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake
    - make

tests:
  - script:
      - if: unix
        then:
          - test -f $PREFIX/lib/libh3${SHLIB_EXT}
          - test -f $PREFIX/include/h3/h3api.h
      - if: win
        then:
          - test -f %PREFIX%\Library\lib\h3.dll
          - test -f %PREFIX%\Library\include\h3\h3api.h
about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Hexagonal hierarchical geospatial indexing system
  homepage: https://github.com/uber/h3
  repository: https://github.com/uber/h3
  documentation: https://uber.github.io/h3/

extra:
  recipe-maintainers:
    - mxr-conda
    - geoHeil
    - benhuff
    - oblute
